spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

check-user-scopes: true